# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='snpdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=20)),
                ('chromosome', models.CharField(max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('reference', models.CharField(max_length=5)),
                ('var_a', models.CharField(max_length=20)),
                ('var_t', models.CharField(max_length=20)),
                ('var_g', models.CharField(max_length=20)),
                ('var_c', models.CharField(max_length=20)),
                ('gwas_sig_report', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
